// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_autotag_slug_ from "./routes/api/autotag/[...slug].ts";
import * as $api_download from "./routes/api/download.ts";
import * as $api_images from "./routes/api/images.ts";
import * as $api_images_retag from "./routes/api/images/retag.ts";
import * as $api_tags from "./routes/api/tags.ts";
import * as $api_users from "./routes/api/users.ts";
import * as $api_users_username_tweets from "./routes/api/users/[username]/tweets.ts";
import * as $autotag_status from "./routes/autotag-status.tsx";
import * as $download_status from "./routes/download-status.tsx";
import * as $images_filepath_ from "./routes/images/[...filepath].ts";
import * as $index from "./routes/index.tsx";
import * as $tags from "./routes/tags.tsx";
import * as $tags_tag_ from "./routes/tags/[tag].tsx";
import * as $users from "./routes/users.tsx";
import * as $users_username_ from "./routes/users/[username].tsx";
import * as $AutotagMenuModal from "./islands/AutotagMenuModal.tsx";
import * as $AutotagStatusPage from "./islands/AutotagStatusPage.tsx";
import * as $DownloadStatusPage from "./islands/DownloadStatusPage.tsx";
import * as $HomePage from "./islands/HomePage.tsx";
import * as $ImageModal from "./islands/ImageModal.tsx";
import * as $Layout from "./islands/Layout.tsx";
import * as $TagImagesPage from "./islands/TagImagesPage.tsx";
import * as $TagsPage from "./islands/TagsPage.tsx";
import * as $UserTweetsPage from "./islands/UserTweetsPage.tsx";
import * as $UsersPage from "./islands/UsersPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/autotag/[...slug].ts": $api_autotag_slug_,
    "./routes/api/download.ts": $api_download,
    "./routes/api/images.ts": $api_images,
    "./routes/api/images/retag.ts": $api_images_retag,
    "./routes/api/tags.ts": $api_tags,
    "./routes/api/users.ts": $api_users,
    "./routes/api/users/[username]/tweets.ts": $api_users_username_tweets,
    "./routes/autotag-status.tsx": $autotag_status,
    "./routes/download-status.tsx": $download_status,
    "./routes/images/[...filepath].ts": $images_filepath_,
    "./routes/index.tsx": $index,
    "./routes/tags.tsx": $tags,
    "./routes/tags/[tag].tsx": $tags_tag_,
    "./routes/users.tsx": $users,
    "./routes/users/[username].tsx": $users_username_,
  },
  islands: {
    "./islands/AutotagMenuModal.tsx": $AutotagMenuModal,
    "./islands/AutotagStatusPage.tsx": $AutotagStatusPage,
    "./islands/DownloadStatusPage.tsx": $DownloadStatusPage,
    "./islands/HomePage.tsx": $HomePage,
    "./islands/ImageModal.tsx": $ImageModal,
    "./islands/Layout.tsx": $Layout,
    "./islands/TagImagesPage.tsx": $TagImagesPage,
    "./islands/TagsPage.tsx": $TagsPage,
    "./islands/UserTweetsPage.tsx": $UserTweetsPage,
    "./islands/UsersPage.tsx": $UsersPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
